---
title: "Untitled"
author: "Sarthak Sunil Dhanke"
date: "2024-12-08"
output: html_document
---

```{r warning=F, message=F}
library(tidyverse)
library(skimr)

```


```{r}
df <- read_csv("Team Stats Per Game.csv")
df |> head()
```


```{r}
df |> skim_without_charts()
```

```{r}
df |> 
    select(season, team, pts_per_game) |> 
    filter(is.na(pts_per_game))
```

```{r}
# Baltimore Bullets ceased to exists from 1955 so there is no season played.
# there may be many more team as such, who season to exits
df |> 
    filter(team == "Baltimore Bullets", season > 1950, season < 1960) |> 
    select(pts_per_game, season)
```


```{r}
cleaned_teams <- df %>%
  mutate(
    team = str_squish(team),                           # Remove extra spaces
    team = str_replace_all(team, "[^a-zA-Z\\s]/", ""), # Remove special characters
    team = str_to_title(team)                          # Convert to Title Case
  )                                           
```

```{r}
cleaned_teams |> filter(startsWith(team, "New Orleans"))
```


```{r}
complete_season <- tibble(season = 1947:2025)

unique_teams <- cleaned_teams |> distinct(team)

expanded_df <- expand_grid(season = complete_season$season, team = unique_teams$team)
expanded_df
# complete_season |> 
#     left_join(
#         df |> 
#             select(season, team, pts_per_game),
#         join_by(all_season == season)
#     )
```

```{r}
cleaned_teams |> 
    select(season, team, pts_per_game) |> 
    write_csv("cleaned_teams.csv")

unique_teams |> 
    write_csv("unique_teams.csv")
```

```{r}
df |> 
    filter(startsWith(team, "Philadelphia Ers"))
```



```{r}
allStars <- read_csv("All-Star Selections.csv", show_col_types = FALSE)
skim_without_charts(allStars)
```


```{r}
# Define mappings for standardization
team_mappings <- c(
  "East" = "East",
  "West" = "West",
  "Giannis" = "Team Giannis",
  "LeBron" = "Team LeBron",
  "Team Durant" = "Team Durant",
  "Team LeBron" = "Team LeBron",
  "Team Giannis" = "Team Giannis",
  "Team Stephen" = "Team Stephen",
  "All Stars" = "Unspecified",
  "Denver" = "Unspecified" # Likely a data error or hosting city, replace accordingly
)

# Standardize team names
cleanedAllStars <- allStars %>%
  mutate(team = str_squish(team), # Remove extra spaces
         team = recode(team, !!!team_mappings))

# Check for remaining inconsistencies
remaining_issues <- cleanedAllStars %>%
  filter(!team %in% c("East", "West", "Team LeBron", "Team Giannis", "Team Durant", "Team Stephen", "Unspecified"))

remaining_issues
```

```{r}
cleanedAllStars |> head()
```

```{r}
cleanedAllStars <- cleanedAllStars %>%
  mutate(
    # Assign East/West based on player's original team
    conference = case_when(
      team %in% c("East", "West") ~ team,
      team %in% c("Team LeBron", "Team Giannis", "Team Durant", "Team Stephen") ~ 
        if_else(str_detect(team, "LeBron|Stephen"), "West", "East"),
      TRUE ~ "Unspecified"
    ),
    # Assign team captains
    team_captain = case_when(
      team %in% c("Team LeBron", "Team Giannis", "Team Durant", "Team Stephen") ~ str_remove(team, "Team "),
      TRUE ~ "N/A"
    )
  )

```

```{r}
write_csv(cleanedAllStars, "cleanedAllStars.csv")
```


```{r}
df_team <- read_csv("Team Totals.csv")
df_oppn <- read_csv("Opponent Totals.csv")
```

```{r}
team_pts <- df_team |> 
  select(team, season, n_games = g, playoffs, pts)
oppn_pts <- df_oppn |> 
  select(team, season, n_games = g, playoffs, opp_pts)
```

```{r}
nrow(team_pts)
nrow(oppn_pts)
```

```{r}
team_pts
```

```{r}
oppn_pts
```


```{r}
skim_without_charts(team_pts)
```

```{r}
skim_without_charts(oppn_pts)
```


```{r}
team_oppn_pts <- team_pts |> 
  cbind(select(oppn_pts, opp_pts))
team_oppn_pts
```


```{r}
team_pts |> 
  filter(is.na(pts))
```

```{r}
team_oppn_pts <- team_oppn_pts |> drop_na()
team_oppn_pts |> filter(is.na(pts)) # drop Baltimore Bullets they were defunct in 1955, but still entered the dataset
```

```{r}
team_oppn_pts <- team_oppn_pts |> 
  mutate(
    pts_diff = pts - opp_pts,
    win = pts_diff > 0
  ) |> 
  filter(team != "League Average")
team_oppn_pts
```




```{r}
team_summaries <- read_csv("Team Summaries.csv")
skim_without_charts(team_summaries)
```

```{r}
team_summaries |> 
  filter(is.na(mov))
```

```{r}
team_summaries |> 
  filter(is.na(w))
```



```{r}
team_summary <- team_summaries |> 
  select(season, team, win = w, loss = l, pts_diff_per_game = mov, playoffs) |> 
  drop_na() |> 
  cbind(select(team_oppn_pts, n_games)) |> 
  select(season, team, win, loss, n_games, pts_diff_per_game, playoffs) |> 
  mutate(
    team = str_squish(team),                           # Remove extra spaces
    team = str_replace_all(team, "[^a-zA-Z\\s]/", ""), # Remove special characters
    team = str_to_title(team)                          # Convert to Title Case
  )  
team_summary
```

```{r}
team_summary |> 
  ggplot(aes(win)) +
  geom_histogram(color = 'white', bins = 30)

```




```{r}
write_csv(team_summary, "team_summary.csv")
```



```{r}
team_summary |> cbind(team_oppn_pts |> select(n_games))
```


```{r}
per_100_poss <- read_csv("Per 100 Poss.csv") |> 
  select(season, tm, o_rtg, d_rtg)
per_100_poss |> skim_without_charts()
```


```{r}
team_abbr <- read_csv("Team Abbrev.csv") |> 
  select(team, abbreviation) |> 
  drop_na() |> 
  unique() |> 
  arrange(team)
team_abbr |> skim_without_charts()
```


# there are more abbreviation than team names and the abbreviation in the team_off_def are just 60 and now we have
to ideas how to join these things.


```{r}
# teams may have more than one abbreviation
team_abbr
```




```{r}
team_off_def <- per_100_poss
team_off_def |> skim_without_charts()
```


```{r}
team_off_def |> 
  full_join(team_abbr |> select(abbreviation, team), join_by(tm == abbreviation)) |> 
  select(tm, team) |> 
  filter(is.na(team)) |> distinct(tm)
```



```{r}
team_off_def <- per_100_poss |> 
  filter(tm != 'TOT')

team_off_def |> skim_without_charts()  
```

```{r}
team_stat <- read_csv("Team Stats Per 100 Poss.csv") |> 
  select(team, abbreviation)

skim_without_charts(team_stat)
```

```{r}
team_off_def |> 
  select(tm) |> 
  unique() |> 
  arrange(tm)
```

```{r}
team_abbr <- team_stat |> 
  distinct() |> 
  arrange(abbreviation)
team_abbr
```


```{r}
team_off_def <- team_off_def |> 
  inner_join(team_abbr, join_by(tm == abbreviation)) |> 
  select(season, team, off_rating = o_rtg, def_rating = d_rtg) |> 
    summarize(
    off_avg = mean(off_rating),
    def_avg = mean(def_rating),
    total_player = n(),
    .by = c(season, team)
  )
skim_without_charts(team_off_def)
```


```{r}
write_csv(team_off_def, "team_off_def.csv")
```


```{r}

```













































































































































































































































































































































































